import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

export const sendOrderNotification = async (order, paymentMethod) => {
  try {
    const itemsList = order.items.map(item => `<li>${item.quantity}x <strong>${item.name}</strong> (${item.weight}) - ₹${item.price * item.quantity}</li>`).join('');
    
    const emailContent = `
      <div style="font-family: sans-serif; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
        <div style="background-color: #ea580c; color: white; padding: 20px; text-align: center;">
          <h1 style="margin: 0; font-size: 24px;">New Order Received! 🍪</h1>
        </div>
        <div style="padding: 20px;">
          <p><strong>Order ID:</strong> ${order._id}</p>
          <p><strong>Payment Method:</strong> ${paymentMethod}</p>
          <p><strong>Total Amount:</strong> <span style="font-size: 18px; color: #ea580c; font-weight: bold;">₹${order.totalAmount}</span></p>
          
          <h3 style="border-bottom: 2px solid #f97316; padding-bottom: 5px;">Customer Details:</h3>
          <p><strong>Name:</strong> ${order.deliveryDetails.fullName}</p>
          <p><strong>Mobile:</strong> ${order.deliveryDetails.mobile}</p>
          <p><strong>Address:</strong> ${order.deliveryDetails.address}, ${order.deliveryDetails.pincode}</p>
          ${order.deliveryDetails.landmark ? `<p><strong>Landmark:</strong> ${order.deliveryDetails.landmark}</p>` : ''}
          
          <h3 style="border-bottom: 2px solid #f97316; padding-bottom: 5px;">Items Ordered:</h3>
          <ul style="padding-left: 20px;">
            ${itemsList}
          </ul>
        </div>
        <div style="background-color: #f9fafb; padding: 15px; text-align: center; font-size: 12px; color: #6b7280;">
          Auto-generated by Mom's Handmade System
        </div>
      </div>
    `;

    // Free tier of Resend only allows sending from onboarding@resend.dev to verified domains/emails
    // Admin email acts as the verified destination.
    const data = await resend.emails.send({
      from: "onboarding@resend.dev",
      to: ["amit4321sg@gmail.com"],
      subject: `New Order Alert: ₹${order.totalAmount} (${paymentMethod})`,
      html: emailContent,
    });

    console.log("📨 Email sent successfully to admin:", data);
  } catch (error) {
    console.error("❌ Error sending email:", error);
  }
};
